// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB31y6B4HRXfIAdz2S908aW5ynefvPt9lM',
    appId: '1:418667716249:web:942f1f3b180fa1976d2208',
    messagingSenderId: '418667716249',
    projectId: 'zenzen-5adb7',
    authDomain: 'zenzen-5adb7.firebaseapp.com',
    storageBucket: 'zenzen-5adb7.firebasestorage.app',
    measurementId: 'G-YSG9RCNC6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI3zIqSA8QefqmmzW_EfziXK0zfYf52SU',
    appId: '1:418667716249:android:62b445da39f3ed746d2208',
    messagingSenderId: '418667716249',
    projectId: 'zenzen-5adb7',
    storageBucket: 'zenzen-5adb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAakxcKAz1g5Ad_sZJ2laFtstFL_g3M-Pw',
    appId: '1:418667716249:ios:dbbeabdb5c0a28366d2208',
    messagingSenderId: '418667716249',
    projectId: 'zenzen-5adb7',
    storageBucket: 'zenzen-5adb7.firebasestorage.app',
    iosBundleId: 'com.example.zenzen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAakxcKAz1g5Ad_sZJ2laFtstFL_g3M-Pw',
    appId: '1:418667716249:ios:dbbeabdb5c0a28366d2208',
    messagingSenderId: '418667716249',
    projectId: 'zenzen-5adb7',
    storageBucket: 'zenzen-5adb7.firebasestorage.app',
    iosBundleId: 'com.example.zenzen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB31y6B4HRXfIAdz2S908aW5ynefvPt9lM',
    appId: '1:418667716249:web:3c7667356098db3f6d2208',
    messagingSenderId: '418667716249',
    projectId: 'zenzen-5adb7',
    authDomain: 'zenzen-5adb7.firebaseapp.com',
    storageBucket: 'zenzen-5adb7.firebasestorage.app',
    measurementId: 'G-MQD6KC5026',
  );
}
