// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:zenzen/data/local/hive_models/fav_documents_model.dart';
import 'package:zenzen/data/local/hive_models/local_user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FavDocumentAdapter());
    registerAdapter(LocalUserAdapter());
  }
}
