// Generated by Hive CE
// Do not modify
// Check in to version control

// ignore_for_file: depend_on_referenced_packages

import 'package:hive_ce/hive.dart';
import 'package:zenzen/data/local/hive_models/local_user_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(UserAdapter());
  }
}
